#!/usr/bin/env python3
"""Verify iPhone runtime safety paths and that preflight is actually packaged."""
from pathlib import Path
import re
import subprocess
import tempfile

root=Path(__file__).resolve().parents[2]
asset=(root/"ios/Bridge/preflight.html").read_text()
server=(root/"ios/Sources/Storage/AssetHTTPServer.swift").read_text()
game=(root/"ios/Sources/UI/GameViewController.swift").read_text()
navigation=(root/"ios/Sources/UI/GameNavigationController.swift").read_text()
prepare=(root/"ios/Scripts/prepare_runtime.sh").read_text()
app=(root/"ios/Sources/App/AppDelegate.swift").read_text()
plist=(root/"ios/Config/Info.plist").read_text()

for required in ["crossOriginIsolated","sharedArrayBuffer","offscreenTransfer","gpuAdapter","wasmCompile","wasmHeader","shaderIndex","gameManifest","titleLogo","audioWorklet"]:
    assert required in asset, required
assert 'name="viewport"' in asset
assert '/ios/preflight.html' in server
assert 'preflight.html' in prepare
assert 'viewport-fit=cover' in prepare
assert 'onPreflight(' in game and 'Runtime requirements failed:' in game
assert 'EngineOptions.launchURL(port: port)' in game
assert 'GameOrientation.request(.landscape' in game
assert 'GameOrientation.request(.portrait' in (root/"ios/Sources/UI/LauncherViewController.swift").read_text()
assert 'GameNavigationController(rootViewController:' in (root / 'ios/Sources/App/SceneDelegate.swift').read_text()
assert 'UIRequiresFullScreen' in plist
assert 'UIInterfaceOrientationLandscapeRight' in plist
assert 'UIInterfaceOrientationPortrait' in plist
assert 'LaunchScreen' in plist
scripts=re.findall(r'<script[^>]*>(.*?)</script>',asset,re.DOTALL|re.IGNORECASE)
assert scripts, "No preflight script"
with tempfile.NamedTemporaryFile(mode="w",suffix=".js") as f:
    f.write("\n".join(scripts)); f.flush()
    subprocess.run(["node","--check",f.name],check=True)

# iPhone 16 regression: use a scene-owned fullscreen UIWindow, not legacy UIScreen.bounds.
scene = (root / "ios/Sources/App/SceneDelegate.swift").read_text()
app_delegate = (root / "ios/Sources/App/AppDelegate.swift").read_text()
launcher = (root / "ios/Sources/UI/LauncherViewController.swift").read_text()
plist = (root / "ios/Config/Info.plist").read_text()
storage = (root / "ios/Sources/Storage/USBStorageManager.swift").read_text()
assert "UIWindow(windowScene: windowScene)" in scene
assert "UIWindow(frame: UIScreen.main.bounds)" not in app_delegate
assert "UIApplicationSceneManifest" in plist and "SceneDelegate" in plist
assert "config.imagePlacement = .top" in launcher
assert "config.titleLineBreakMode = .byTruncatingTail" in launcher
assert "playButton.isEnabled = true" in launcher
assert "playgta5.com" in storage and "contentsOfDirectory" in storage
project = (root / "ios/project.yml").read_text()
assert "GENERATE_INFOPLIST_FILE: NO" in project, "Use the committed Info.plist, not autogenerated settings"
assert 'INFOPLIST_FILE: "$(SRCROOT)/Config/Info.plist"' in project
assert "    info:" not in project, "XcodeGen info.path would overwrite the committed launch plist"
assert "TARGETED_DEVICE_FAMILY: \"1\"" in project
print("PASS: native iPhone scene sizing, compact toolbar layout, USB folder traversal, and picker recovery")
print("PASS: runtime prereq probes, original asset HEAD/range checks, iPhone portrait/landscape policy, JavaScript syntax")
