#!/usr/bin/env python3
"""Verify iPhone runtime safety paths and that preflight is actually packaged."""
from pathlib import Path
import re
import subprocess
import tempfile

root=Path(__file__).resolve().parents[2]
asset=(root/"ios/Bridge/preflight.html").read_text()
server=(root/"ios/Sources/Storage/AssetHTTPServer.swift").read_text()
game=(root/"ios/Sources/UI/GameViewController.swift").read_text()
navigation=(root/"ios/Sources/UI/GameNavigationController.swift").read_text()
prepare=(root/"ios/Scripts/prepare_runtime.sh").read_text()
app=(root/"ios/Sources/App/AppDelegate.swift").read_text()
plist=(root/"ios/Config/Info.plist").read_text()

for required in ["crossOriginIsolated","sharedArrayBuffer","offscreenTransfer","gpuAdapter","wasmCompile","wasmHeader","shaderIndex","gameManifest","titleLogo","audioWorklet"]:
    assert required in asset, required
assert 'name="viewport"' in asset
assert '/ios/preflight.html' in server
assert 'preflight.html' in prepare
assert 'viewport-fit=cover' in prepare
assert 'onPreflight(' in game and 'Runtime requirements failed:' in game
assert 'EngineOptions.launchURL(port: port)' in game
assert 'GameOrientation.request(.landscape' in game
assert 'GameOrientation.request(.portrait' in (root/"ios/Sources/UI/LauncherViewController.swift").read_text()
assert 'GameNavigationController(rootViewController:' in (root / 'ios/Sources/App/SceneDelegate.swift').read_text()
assert 'UIRequiresFullScreen' in plist
assert 'UIInterfaceOrientationLandscapeRight' in plist
assert 'UIInterfaceOrientationPortrait' in plist
assert 'LaunchScreen' in plist
scripts=re.findall(r'<script[^>]*>(.*?)</script>',asset,re.DOTALL|re.IGNORECASE)
assert scripts, "No preflight script"
with tempfile.NamedTemporaryFile(mode="w",suffix=".js") as f:
    f.write("\n".join(scripts)); f.flush()
    subprocess.run(["node","--check",f.name],check=True)

# iPhone 16 regression: use a scene-owned fullscreen UIWindow, not legacy UIScreen.bounds.
scene = (root / "ios/Sources/App/SceneDelegate.swift").read_text()
app_delegate = (root / "ios/Sources/App/AppDelegate.swift").read_text()
launcher = (root / "ios/Sources/UI/LauncherViewController.swift").read_text()
plist = (root / "ios/Config/Info.plist").read_text()
storage = (root / "ios/Sources/Storage/USBStorageManager.swift").read_text()
assert "UIWindow(windowScene: windowScene)" in scene
assert "UIWindow(frame: UIScreen.main.bounds)" not in app_delegate
assert "UIApplicationSceneManifest" in plist and "SceneDelegate" in plist
assert "config.imagePlacement = .top" in launcher
assert "config.titleLineBreakMode = .byTruncatingTail" in launcher
assert "playButton.isEnabled = true" in launcher
assert "playgta5.com" in storage and "contentsOfDirectory" in storage
project = (root / "ios/project.yml").read_text()
assert "GENERATE_INFOPLIST_FILE: NO" in project, "Use the committed Info.plist, not autogenerated settings"
assert 'INFOPLIST_FILE: "$(SRCROOT)/Config/Info.plist"' in project
assert "    info:" not in project, "XcodeGen info.path would overwrite the committed launch plist"
assert "TARGETED_DEVICE_FAMILY: \"1\"" in project
# Regression: a Files folder tap that does not deliver its delegate URL must not
# be confused with a successful security-scoped folder grant.
assert 'forOpeningContentTypes: [.item, .folder], asCopy: false' in launcher
assert 'forOpeningContentTypes: [.item, .folder], asCopy: true' in launcher
assert 'picker.allowsMultipleSelection = mode == .folder' in launcher
assert 'livecontainer_public_compat=1' in launcher
assert 'urls.first(where: { $0.lastPathComponent == "playgta5.com" })' in launcher
assert 'forOpeningContentTypes: [.folder], asCopy: false' not in launcher
assert 'forOpeningContentTypes: [.html], asCopy: false' not in launcher
assert 'FILES CALLBACK RECEIVED' in launcher
assert "didPickDocumentAt url: URL" in launcher, "Legacy single-file provider compatibility"
assert "LEGACY_FILES_CALLBACK" in launcher
assert 'infoDictionary?["CFBundleVersion"]' in launcher, "Visible build number needed to detect stale SideStore install"
assert "<key>CFBundleVersion</key><string>8</string>" in plist
assert '@objc private func chooseFolder() { openPicker(.folder) }' in launcher
assert '@objc private func testFilesPicker() { openPicker(.diagnosticText) }' in launcher
assert '@objc private func chooseIndexFile() { openPicker(.indexFile) }' in launcher
assert 'GTAiOS-Picker-Test.txt' in launcher
assert 'prepareDiagnosticTextFile()' in launcher
assert 'forOpeningContentTypes: [.item]' not in launcher
assert 'PICKER_DIAGNOSTIC_SUCCEEDED' in launcher
assert 'PICKER_GONE_WITHOUT_CALLBACK' in launcher
assert 'UIAlertController(\n            title: "Connect game files"' not in launcher
assert 'chooseIndexFile(_ chosen: URL)' in storage
assert 'NSFileCoordinator(filePresenter: nil)' in storage
assert 'read(upToCount: 4)' in storage
assert 'case fileProviderDeniedSiblingAccess(String)' in storage
# No blocking external drive reads from UIKit picker callbacks or launcher refresh.
callback = launcher.split("func documentPicker(_ controller: UIDocumentPickerViewController, didPickDocumentsAt urls: [URL])")[1].split("private func showPickerResult")[0]
assert "chooseAsync(url, fromFile:" in callback
assert "USB_VALIDATION_BEGIN" in callback and "USB_VALIDATION_TIMEOUT" in callback
assert "USBStorageManager.shared.choose(url)" not in callback
assert "USBStorageManager.shared.chooseIndexFile(url)" not in callback
assert "FileManager.default" not in callback and "NSFileCoordinator" not in callback.replace("// resolution, NSFileCoordinator", ""), "USB I/O must stay off UIKit main"
assert "worker.async" in storage and "private init()" in storage
assert "stateLock" in storage and "scanStartupAssets(in:" in storage
assert "private func scanStartupAssets(in gameRoot:" in storage
assert "contentsOfDirectory(\\n                    at: root.appendingPathComponent(\\\"data\\\")" not in storage, "Do not enumerate huge data folder"
assert 'UIImage(contentsOfFile: file.path)' not in launcher, "No blocking USB artwork reads from UI refresh"
print("PASS: nonblocking USB validation, immediate picker callback, timed recovery")
print("PASS: LiveContainer public-API-compatible broad item+folder picker, multi-folder selection, copy-free USB")
print("PASS: native iPhone scene sizing, compact toolbar layout, USB folder traversal, and picker recovery")
print("PASS: runtime prereq probes, original asset HEAD/range checks, iPhone portrait/landscape policy, JavaScript syntax")
